name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  build:  

    runs-on: macos-latest  // iOS 플랫폼에서 실행한다는 뜻

    steps:
    - uses: actions/checkout@v3  // repository에 체크아웃해서 job이 접근 가능하게 한다는 뜻 (Github Actions에서 미리 정의한 명령)
    - name: Build Xcode  // 실행할 작업 이름
      run: |
        xcodebuild clean test -project WhatWeEat.xcodeproj \
        -scheme WhatWeEat \
        -destination 'platform=iOS Simulator,name=iPhone 13,OS=latest'
